### ISSUE TITLE
Qt 4.x

### ISSUE THREAD

**Issue by Gmirabile97** [basavarajnavalgund/hector-quadrotor#1]
`CMake Error at /usr/share/cmake-3.16/Modules/FindQt4.cmake:1314 (message):
  Found unsuitable Qt version "5.12.8" from /usr/bin/qmake, this code
  requires Qt 4.x`

during catkin_make on Ubuntu 20.04

**Comment by basavarajnavalgund** [comment]
It'll work well for Ubuntu 16.04 and Ubuntu 18.04. I haven't tested for 20.04..

**Comment by Gmirabile97** [comment]
Thank you anyway.
